[2025-02-01 01:49:48 +0300] [2015] [INFO] Starting gunicorn 21.2.0
[2025-02-01 01:49:48 +0300] [2015] [INFO] Starting Musicstagram server with Gunicorn ðŸš€
[2025-02-01 01:49:48 +0300] [2015] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-02-01 01:49:48 +0300] [2015] [ERROR] Retrying in 1 second.
[2025-02-01 01:49:49 +0300] [2015] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-02-01 01:49:49 +0300] [2015] [ERROR] Retrying in 1 second.
[2025-02-01 01:49:50 +0300] [2015] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-02-01 01:49:50 +0300] [2015] [ERROR] Retrying in 1 second.
[2025-02-01 01:49:51 +0300] [2015] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-02-01 01:49:51 +0300] [2015] [ERROR] Retrying in 1 second.
[2025-02-01 01:49:52 +0300] [2015] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-02-01 01:49:52 +0300] [2015] [ERROR] Retrying in 1 second.
[2025-02-01 01:49:53 +0300] [2015] [ERROR] Can't connect to ('0.0.0.0', 5000)
[2025-02-01 01:50:58 +0300] [2264] [DEBUG] Current configuration:
  config: gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5000']
  backlog: 2048
  workers: 17
  worker_class: gevent
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: True
  sendfile: None
  reuse_port: False
  chdir: /Users/aihub/AI Empire HQ/Archived Chaos/emin_Draft
  daemon: False
  raw_env: []
  pidfile: musicstagram.pid
  worker_tmp_dir: None
  user: 503
  group: 20
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: logs/access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: unix:///var/run/syslog
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: musicstagram
  default_proc_name: musicstagram:app
  pythonpath: .
  paste: None
  on_starting: <function on_starting at 0x103596c10>
  on_reload: <function on_reload at 0x103596d30>
  when_ready: <function when_ready at 0x103745820>
  pre_fork: <function pre_fork at 0x103745700>
  post_fork: <function post_fork at 0x103596ca0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x10360b1f0>
  worker_int: <function worker_int at 0x1037458b0>
  worker_abort: <function worker_abort at 0x103745940>
  pre_exec: <function pre_exec at 0x103745790>
  pre_request: <function PreRequest.pre_request at 0x10360b670>
  post_request: <function PostRequest.post_request at 0x10360b700>
  child_exit: <function ChildExit.child_exit at 0x10360b820>
  worker_exit: <function WorkerExit.worker_exit at 0x10360b940>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x10360ba60>
  on_exit: <function OnExit.on_exit at 0x10360bb80>
  ssl_context: <function NewSSLContext.ssl_context at 0x10360bca0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2025-02-01 01:50:58 +0300] [2264] [INFO] Starting gunicorn 21.2.0
[2025-02-01 01:50:58 +0300] [2264] [INFO] Starting Musicstagram server with Gunicorn ðŸš€
[2025-02-01 01:50:58 +0300] [2264] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-02-01 01:50:58 +0300] [2264] [DEBUG] connection to ('0.0.0.0', 5000) failed: [Errno 48] Address already in use
[2025-02-01 01:50:58 +0300] [2264] [ERROR] Retrying in 1 second.
[2025-02-01 01:50:59 +0300] [2264] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-02-01 01:50:59 +0300] [2264] [DEBUG] connection to ('0.0.0.0', 5000) failed: [Errno 48] Address already in use
[2025-02-01 01:50:59 +0300] [2264] [ERROR] Retrying in 1 second.
[2025-02-01 01:51:00 +0300] [2264] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-02-01 01:51:00 +0300] [2264] [DEBUG] connection to ('0.0.0.0', 5000) failed: [Errno 48] Address already in use
[2025-02-01 01:51:00 +0300] [2264] [ERROR] Retrying in 1 second.
[2025-02-01 01:51:01 +0300] [2264] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-02-01 01:51:01 +0300] [2264] [DEBUG] connection to ('0.0.0.0', 5000) failed: [Errno 48] Address already in use
[2025-02-01 01:51:01 +0300] [2264] [ERROR] Retrying in 1 second.
[2025-02-01 01:51:02 +0300] [2264] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-02-01 01:51:02 +0300] [2264] [DEBUG] connection to ('0.0.0.0', 5000) failed: [Errno 48] Address already in use
[2025-02-01 01:51:02 +0300] [2264] [ERROR] Retrying in 1 second.
[2025-02-01 01:51:03 +0300] [2264] [ERROR] Can't connect to ('0.0.0.0', 5000)
[2025-02-12 01:08:22 +0300] [63713] [INFO] Starting gunicorn 21.2.0
[2025-02-12 01:08:22 +0300] [63713] [INFO] Starting Musicstagram server with Gunicorn ðŸš€
[2025-02-12 01:08:22 +0300] [63713] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-02-12 01:08:22 +0300] [63713] [ERROR] Retrying in 1 second.
[2025-02-12 01:08:23 +0300] [63713] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-02-12 01:08:23 +0300] [63713] [ERROR] Retrying in 1 second.
[2025-02-12 01:08:24 +0300] [63713] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-02-12 01:08:24 +0300] [63713] [ERROR] Retrying in 1 second.
[2025-02-12 01:08:25 +0300] [63713] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-02-12 01:08:25 +0300] [63713] [ERROR] Retrying in 1 second.
[2025-02-12 01:08:26 +0300] [63713] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-02-12 01:08:26 +0300] [63713] [ERROR] Retrying in 1 second.
[2025-02-12 01:08:27 +0300] [63713] [ERROR] Can't connect to ('0.0.0.0', 5000)
